name: Thinking, Learning.
description: >
  Shrey Shrivastava
about: >
  Shrey Shrivastava
master_repo: false
url: "http://shreyshrivastava4799.me"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed', 'jekyll-seo-tag']

paginate: 4

logo: '/assets/logo.png'
disqus_shortname:

rtl: false
owner:
  email:          "shrivastava.shrey@ymail.com"
  twitter:        shrey4799
  github:         https://github.com/shreyshrivastava4799
  linkedin:       https://www.linkedin.com/in/shrey-shrivastava-2a6716116/
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
